### PR TITLE
relates to #178: adapt countDocuments per spec, improve tests

### PR DESCRIPTION
**Pull request by ivansenic**
**What this PR does**:

Adaptation to spec for the `countDocuments`, including test improvements.

* [x] adapted status to `count` as per spec, from `counted_documents` (@kathirsvn fyi)
* [x] removed option class from command as per spec no options exists
* improved tests:
   * [x] added resolver test
   * [ ] added error case in operation tests
   * [x] several fixes for the integration tests:
      * assert no errors & data
      * few tests were missing `@Test` annotation
      * improved readability
      * [x] remove test order - not needed
* [x] fixed swagger examples

**Which issue(s) this PR fixes**:
Relates to #178.

### CODE REVIEW

**Comment by maheshrajamani** [comment]
@vkarpov15 Can you confirm if countDocuments response element has to be count or counted_documents? Remember seeing counted_documents response name in some documentation.

**Review by maheshrajamani — APPROVED** [review]

**Review by vkarpov15 — APPROVED** [review]

**Comment by tatu-at-datastax** [comment]
I was trying to figure out Mongo equivalent, but `countDocuments()` documentation mostly referes to mongosh command; like:

https://www.geeksforgeeks.org/mongodb-countdocuments-method/

but regardless seems to just return raw numeric count, not a BSON Object.
That is not a good response for various reasons, but I was hoping to find better definition of what Mongoose would expect if not plain number.

**Comment by ivansenic** [comment]
@tatu-at-datastax @maheshrajamani I am not sure if I can merge this now? Will you provide your reviews?

**Comment by vkarpov15** [comment]
@tatu-at-datastax Mongoose expects `countDocuments()` to return a number. However, if it makes more sense for Stargate to return `{ count: 2 }` as opposed to just `2`, that's fine, I think it isn't a big deal for the stargate-mongoose driver to transform this result.

**Comment by ivansenic** [comment]
OK I am merging this when I fix remaining tasks.

**Comment by tatu-at-datastax** [comment]
Sorry, I am fine with the change, just wanted to verify I understood if it's different from Mongo handling; and if so if it is intentional and not accidental. Since it's intentional that's fine.

**Review by tatu-at-datastax — APPROVED** [review]

**Comment by ivansenic** [comment]
Will merge this, and add the error test case when updating SG to `v2.0.9`.

**Pull request merged**
