### PR TITLE
CQLSessionCache - evictionListener changed to removalListener

### LINKED ISSUE #645: Closing session with possible in-flight queries
In the native cql driver based implementation, the driver cqlsession object is getting closed on getting evicted from the cache. But there is no check if there are any queries in-flight before closing the session. In other words, is there a graceful close for session?

### PR DESCRIPTION
**Pull request by kathirsvn**
**What this PR does**:

In `CQLSessionCache`, Caffeine cache's `evictionListener` is changed to `removalListener`.

1. The configured removal listener is invoked after the entry has been removed from the cache, so any session that gets evicted will first be removed from the cache so it will no longer be found for any key.
2. The configured removal listener closes the `CqlSession` that is passed which is a graceful shut down (i.e. any in-flight queries will be completed before shutting down the channels)

**Which issue(s) this PR fixes**:
Fixes #645 

**Checklist**
- [X] Changes manually tested
- [X] Automated Tests added/updated
- [X] Documentation added/updated
- [X] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by kathirsvn** [comment]
@stargate/core The IT for the native image fails in this PR.
https://github.com/stargate/jsonapi/actions/runs/7195421867/job/19598287312?pr=730.

I reported the same [here](https://github.com/quarkusio/quarkus/issues/30744#issuecomment-1855093527). Can we disable native image test for now until this is fixed on the Quarkus side?

**Comment by jeffreyscarpenter** [comment]
> Can we disable native image test for now until this is fixed on the Quarkus side?

Yes, I agree this makes sense @kathirsvn

**Comment by kathirsvn** [comment]
Excluded the Native Image CI tests and the tests look good now.

**Review by Yuqi-Du — APPROVED** [review]
LGTM

**Pull request merged**
