### PR TITLE
Fix native image building with datastax driver dependency

### LINKED ISSUE #597: Native Image build failure
Once we add `com.datastax.oss:java-driver-core` dependency, native image building fails with below error
```
com.oracle.svm.core.util.UserError$UserException: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
Detailed message:
Trace: Object was reached by
  reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of constant 
    java.net.InetSocketAddress$InetSocketAddressHolder@7eda691c: /127.0.0.1:9042
  reading field java.net.InetSocketAddress.holder of constant 
    java.net.InetSocketAddress@5ce0e1c8: /127.0.0.1:9042
  reading field com.datastax.oss.driver.internal.core.metadata.DefaultEndPoint.address of constant 
    com.datastax.oss.driver.internal.core.metadata.DefaultEndPoint@cb54a5b: /127.0.0.1:9042
  scanning root com.datastax.oss.driver.internal.core.metadata.DefaultEndPoint@cb54a5b: /127.0.0.1:9042 embedded in 
    com.datastax.oss.driver.internal.core.metadata.MetadataManager.addContactPoints(MetadataManager.java:138)
  parsing method com.datastax.oss.driver.internal.core.metadata.MetadataManager.addContactPoints(MetadataManager.java:136) reachable via the parsing context
    at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:382)
    at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
    at com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
    at com.datastax.oss.driver.internal.core.session.DefaultSession$$Lambda$2757/0x00000007c2595cf0.run(Unknown Source)
    at java.lang.Shutdown.runHooks(Shutdown.java:130)
    at java.lang.Shutdown.exit(Shutdown.java:173)
    at com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:334)
    at static root method.(Unknown Source)


	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:798)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
------------------------------------------------------------------------------------------------------------------------
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)

```

### PR DESCRIPTION
**Pull request by kathirsvn**
**What this PR does**:

- Datastax java-driver dependency adds a class called `com.datastax.oss.driver.internal.core.metadata.MetadataManager` which initializes `java.net.InetAddress`

- The `native-image` tool used for building the native image expects `java.net.InetAddress` to be always initialized at runtime since version `19.3.0` (https://stackoverflow.com/questions/63328298/how-do-you-debug-a-no-instances-of-are-allowed-in-the-image-heap-when-buil)

- Quarkus provides a way to pass additional args to pass to `native-image` via  [quarkus.native.additional-build-args](https://quarkus.io/guides/building-native-image#quarkus-native-pkg-native-config_quarkus.native.additional-build-args)
where we can pass the classes to be initialized at runtime

- So passing below arg fixes the native image building

```
-Dquarkus.native.additional-build-args='--initialize-at-run-time=com.datastax.oss.driver.internal.core.metadata.MetadataManager'
```

**Which issue(s) this PR fixes**:
Fixes #597 

**Checklist**
- [X] Changes manually tested
- [X] Automated Tests added/updated
- [X] Documentation added/updated
- [X] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by Yuqi-Du** [comment]
I am thinking could we move this -Dquarkus.native.additional-build-args to [configuration.yaml](https://quarkus.io/guides/building-native-image#quarkus-native-pkg-native-config_quarkus.native.additional-build-args:~:text=these%20monitoring%20options.-,Configuring%20the%20Native%20Executable,-There%20are%20a)?
Since if every time we find some classes which need a runtime initialization, we add the command, the command will be longer?

Not very sure.

**Comment by kathirsvn** [comment]
Good point @Yuqi-Du. Also, less change :-) Updated in this commit [de2a049](https://github.com/stargate/jsonapi/pull/598/commits/de2a04949f78100c467ef1ea0f8d7bfb62ec8043).

**Review by Yuqi-Du — APPROVED** [review]
LGTM!!

**Review by tatu-at-datastax — APPROVED** [review]
LGTM -- thank you for adding a reference to issue, important to know where this setting came from (and why)

**Pull request merged**
