### PR TITLE
Simplify construction of JsonApiException, reduce boilerplate code

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Adds a simplified helper method in `ErrorCode` for constructing standardized exception messages, updates some of usage.

**Which issue(s) this PR fixes**:
N/A

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by jeffreyscarpenter — COMMENTED** [review]
Does this change the format of any of the error messages? Looks like it might. Is there potential impact to downstream clients who have test cases matching specific patterns?

**Review by Yuqi-Du — APPROVED** [review]
Looks great! Thanks.

**Comment by Yuqi-Du** [comment]
> Does this change the format of any of the error messages? Looks like it might. Is there potential impact to downstream clients who have test cases matching specific patterns?

looks like, Tatu only modifies messages related to` no_index`, which merged only in lasted week.
IMO, won't be a big issue.

**Comment by tatu-at-datastax** [comment]
> Does this change the format of any of the error messages? Looks like it might. Is there potential impact to downstream clients who have test cases matching specific patterns?

Only for no-index, which hasn't hit production yet.

**Pull request merged**
