### PR TITLE
Swagger vector search

### PR DESCRIPTION
**Pull request by maheshrajamani**
**What this PR does**:
Added swagger examples for vector search

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by tatu-at-datastax — APPROVED** [review]

**Comment by tatu-at-datastax** [comment]
@maheshrajamani Looks like concurrent change to vector size mismatch error message causes fails here. May be able to just merge from `main`?

**Comment by maheshrajamani** [comment]
>

**Comment by maheshrajamani** [comment]
> @maheshrajamani Looks like concurrent change to vector size mismatch error message causes fails here. May be able to just merge from `main`?

Yes, waiting for the stargate release, once we bump up the stargate version the IT errors should go away.

**Comment by tatu-at-datastax** [comment]
@maheshrajamani Stargate v2.1.0-ALPHA-7 is now released and json-api `main` updated.

**Pull request merged**
