### PR TITLE
Bug fix for array size filter for `0` length

### LINKED ISSUE #862: Filtering array element by $size: 0 doesn't seem to work
Sending the following query:

```
{
  "find": {
    "filter": {
      "tags": {
        "$size": 0
      }
    }
  }
}
```

returns all documents where `tags` is **not** an array of length 0. I first noticed this while working on test failures for this PR: https://github.com/stargate/stargate-mongoose/pull/183, looks like this changed between v1.0.0-BETA-6 and v1.0.0. Maybe with `$not` handling?

### PR DESCRIPTION
**Pull request by maheshrajamani**
**What this PR does**:
Bug fix for array size filter for `0` length

**Which issue(s) this PR fixes**:
Fixes #862 

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by Yuqi-Du — APPROVED** [review]
LGTM

**Review by tatu-at-datastax — APPROVED** [review]

**Comment by tatu-at-datastax** [comment]
Quick question: do we know what happens if negative value is given? Is that valid argument?

**Comment by maheshrajamani** [comment]
> Quick question: do we know what happens if negative value is given? Is that valid argument?

We don't support -ve number for `$size`. It's coded for it internally to support pushdown of logical `$not` operator.

**Comment by tatu-at-datastax** [comment]
@maheshrajamani That makes sense. However, I wonder then why did the original report suggest that `$size` with `0` return everything BUT 0-sized array documents -- if it was translated to `$not` (which I think is what was happening due to wrong comparison), shouldn't it have returned nothing?

**Comment by vkarpov15** [comment]
LGTM. I was concerned for a minute that this change meant that `{ $not: { $size: 0 } }` would no longer work, but it looks like we don't support `$not` with `$size` currently. So no new issues.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 I had the same question and @maheshrajamani explained how it worked so yeah, great minds think alike etc. :)

**Pull request merged**
