### PR TITLE
Fix #633: prevent use of "$similarity" in projection

### LINKED ISSUE #633: $similarity accepted within projection
Dollar-fields raise an `UNSUPPORTED_PROJECTION_PARAM` error all right, while (perhaps unexpected since there's the `includeSimilarity` option already to control that) as special case `"$similarity": 1` is accepted by the find methods.

ERROR:

```
curl -XPOST   "${ASTRA_DB_API_ENDPOINT}/api/json/v1/default_keyspace/astra_db_quickstart"   -H "X-Cassandra-Token: $ASTRA_DB_APPLICATION_TOKEN"   -H "Content-Type: application/json"   -d '{
    "findOne": {
      "sort" : {"$vector" : [0.15, 0.1, 0.1, 0.35, 0.55]},
      "projection": {"text": 1, "$similarity": 1, "$pizza": 1},
      "options" : {
        "includeSimilarity" : true
      }
    }
  }' | jq
```

NO ERRORS (just take out the `, "$pizza": 1` bit):

```
curl -XPOST   "${ASTRA_DB_API_ENDPOINT}/api/json/v1/default_keyspace/astra_db_quickstart"   -H "X-Cassandra-Token: $ASTRA_DB_APPLICATION_TOKEN"   -H "Content-Type: application/json"   -d '{
    "findOne": {
      "sort" : {"$vector" : [0.15, 0.1, 0.1, 0.35, 0.55]},
      "projection": {"text": 1, "$similarity": 1},
      "options" : {
        "includeSimilarity" : true
      }
    }
  }' | jq
```

### PR DESCRIPTION
**Pull request by tatu-at-datastax**
**What this PR does**:

Prevents use of `$similarity` in Projection clause, since it is not a real field and there is different mechanism  for inclusion via `options`.

**Which issue(s) this PR fixes**:
Fixes #633

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by Yuqi-Du** [comment]
Could you please also delete two corresponding NB tests 
https://github.com/stargate/jsonapi/blob/cf3f5789862aa7c618edfcdb43a859f449ed3235/fallout/vector-test-nosqlbench.yaml#L132C15-L132C65
https://github.com/stargate/jsonapi/blob/cf3f5789862aa7c618edfcdb43a859f449ed3235/nosqlbench/http-jsonapi-vector-crud.yaml#L139

Perhaps just delete the ops.

LGTM.

**Review by Yuqi-Du — APPROVED** [review]

**Comment by tatu-at-datastax** [comment]
> Could you please also delete two corresponding NB tests
> 
> https://github.com/stargate/jsonapi/blob/cf3f5789862aa7c618edfcdb43a859f449ed3235/fallout/vector-test-nosqlbench.yaml#L119C1-L119C1
> 
> https://github.com/stargate/jsonapi/blob/cf3f5789862aa7c618edfcdb43a859f449ed3235/nosqlbench/http-jsonapi-vector-crud.yaml#L139
> 
> Perhaps just delete the ops.
> 
> LGTM.

I changed to use `options` instead: does this look good now?

**Comment by Yuqi-Du** [comment]
> > Could you please also delete two corresponding NB tests
> > https://github.com/stargate/jsonapi/blob/cf3f5789862aa7c618edfcdb43a859f449ed3235/fallout/vector-test-nosqlbench.yaml#L119C1-L119C1
> > https://github.com/stargate/jsonapi/blob/cf3f5789862aa7c618edfcdb43a859f449ed3235/nosqlbench/http-jsonapi-vector-crud.yaml#L139
> > 
> > Perhaps just delete the ops.
> > LGTM.
> 
> I changed to use `options` instead: does this look good now?

Perfect! Thanks!

**Comment by eolivelli** [comment]
FYI It seems that this change broke the LangChain integration, see this patch
https://github.com/langchain-ai/langchain/pull/13512

Currently with LangChain you cannot use the JSON API

**Comment by tatu-at-datastax** [comment]
@eolivelli Thank you for reporting this. It is unfortunate, I'll let others know so that Langchain integration can be fixed. At this point we hope to solidify API but there may be some last breaking changes (in some cases we can keep backwards compatibility; here unfortunaely not).

**Review by vkarpov15 — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
