### PR TITLE
Do not return HTTP 504 Gateway Timeout on DB timeout 

### PR DESCRIPTION
**Pull request by Yuqi-Du**
when we get a timeout from the DB we are returning a HTTP 504 gateway timeout. This is incorrect, we should return a status 200 and an error, which we do in many cases.

**Which issue(s) this PR fixes**:
Jira:  https://datastax.jira.com/browse/C2-3212

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by amorton — CHANGES_REQUESTED** [review]
please also handle the case where it is returning BAD_GATEWAY on UNAVAILABLE

do the tests confirm that when these things happen we return HTTP 200 and the error list has the appropriate errors ?

**Comment by Yuqi-Du** [comment]
> BAD_GATEWAY

Yep, this is from the old bridge logic, remove that part now.

**Review by maheshrajamani — APPROVED** [review]
LGTM based on yesterday's discussion.

**Review by tatu-at-datastax — APPROVED** [review]
Looks good. Would be great if this could be tested with IT but not sure how that could be done.

**Review by vkarpov15 — COMMENTED** [review]
LGTM :+1:

**Pull request merged**
