### PR TITLE
fix changelog

### PR DESCRIPTION
**Pull request by Yuqi-Du**
**What this PR does**:
fix changelog update script

**Which issue(s) this PR fixes**:
Fixes [430](https://github.com/stargate/jsonapi/issues/430)

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
Looks like CI stuck? Will close, re-open to try to get unstuck.

**Comment by tatu-at-datastax** [comment]
@Yuqi-Du yeah, forgot to mention that close/re-open did not work. Not sure what is going on.

**Comment by jeffreyscarpenter** [comment]
This PR doesn't change any files that match the trigger for the CI workflow, that's why the required checks don't run. @tatu-at-datastax @Yuqi-Du 

```
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/continuous-integration.yaml'
```

You should be able to trigger the workflow manually for this branch. I think GH will pick up that the checks have run after that. If that doesn't work you might have to make a trivial change to some file that will trigger the run.

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter I should have realized this is the case, thank you for pointing this out.

Then again, this change won't be tested by any of the checks anyway so I guess it all evens out.

**Review by maheshrajamani — APPROVED** [review]

**Pull request merged**
